Repository ExeterTeam25/group-software-project, pull requests merged in 2022-02, with the labels that each got.

#4 locations from json file added to map
  latLong.json
  map.html
  map.py
Labels: enhancement

#7 Interactive map implemented
  group_project1/base/Resources/latLong.json
  group_project1/base/templates/base/home.html
  group_project1/base/templates/base/login_register.html
  group_project1/base/views.py
  map.html
  map.py
Labels: enhancement

#15 Failed login
  README.md
  group_project1/base/migrations/0009_accessattemptaddons.py
  group_project1/base/models.py
  group_project1/base/templates/base/home.html
  group_project1/base/views.py
  group_project1/group_project/settings.py
Labels: enhancement

#18 Forget password
  README.md
  group_project1/base/forms.py
  group_project1/base/templates/base/login_register.html
  group_project1/base/templates/password/password_reset.html
  group_project1/base/templates/password/password_reset_complete.html
  group_project1/base/templates/password/password_reset_confirm.html
  group_project1/base/templates/password/password_reset_done.html
  group_project1/base/templates/password/password_reset_email.txt
  group_project1/base/urls.py
  group_project1/base/views.py
  group_project1/group_project/settings.py
Labels: enhancement

#20 Sso v2
  .gitignore
  README.md
  group_project1/auth_helper.py
  group_project1/base/migrations/0013_merge_20220226_1706.py
  group_project1/base/migrations/0014_merge_20220226_1711.py
  group_project1/base/templates/base/home.html
  group_project1/base/templates/base/login_register.html
  group_project1/base/urls.py
  group_project1/base/views.py
  group_project1/graph_helper.py
Labels: enhancement

#22 Add sso back
  group_project1/base/templates/base/login_register.html
Labels: documentation

#24 Interactive map rewrite
  README.md
  group_project1/base/Resources/latLong.json
  group_project1/base/templates/base/home.html
  group_project1/base/urls.py
  group_project1/base/views.py
  group_project1/static/images/userMarker.jpg
Labels: enhancement

#27 fix for macos and linux OS not running properly
  group_project1/base/views.py
Labels: Fixed Bug

#26 Likes
  group_project1/base/admin.py
  group_project1/base/forms.py
  group_project1/base/migrations/0015_responses_liked_likes.py
  group_project1/base/models.py
  group_project1/base/templates/base/challengeResponses.html
  group_project1/base/templates/base/myResponses.html
  group_project1/base/templates/base/recentActivity.html
  group_project1/base/templates/base/userResponses.html
  group_project1/base/urls.py
  group_project1/base/views.py
  group_project1/templates/like.html
Labels: New Feature, Documentation

#30 Adding map to challenge creation screen
  group_project1/base/templates/base/createChallenge.html
  group_project1/base/templates/base/home.html
Labels: Changed Feature, Documentation

#33 password reset no redirects to localhost
  UniExplore/base/migrations/0018_alter_responses_challenge.py
  UniExplore/base/views.py
Labels: Fixed Bug

#35 Updating Readme
  README.md
Labels: Documentation

#36 Update README.md
  README.md
Labels: Documentation

#37 Readme updated
  README.md
Labels: Documentation, Styling
