Repository ExeterTeam25/group-software-project, pull requests merged in 2022-03, with the labels that each got.

#40 Cleaned up views.py imports
  UniExplore/base/views.py
Labels: Refactoring

#41 Branch correction
  README.md
  UniExplore/base/views.py
Labels: Refactoring

#38 Location spoof mode added to home menu
  UniExplore/base/templates/base/home.html
Labels: New Feature, Refactoring

#46 Login/register form styling
  UniExplore/base/templates/base/login_register.html
Labels: Styling

#48 Changed how you install all the required modules
  README.md
  requirements.txt
Labels: Documentation

#52 Styling
  UniExplore/base/templates/base/login_register.html
Labels: Fixed Bug, Styling

#54 added authors
  UniExplore/auth_helper.py
  UniExplore/base/admin.py
  UniExplore/base/apps.py
  UniExplore/base/decorators.py
  UniExplore/base/forms.py
  UniExplore/base/models.py
  UniExplore/base/templates/base/challengeResponses.html
  UniExplore/base/templates/base/createChallenge.html
  UniExplore/base/templates/base/createResponse.html
  UniExplore/base/templates/base/home.html
  UniExplore/base/templates/base/leaderboard.html
  UniExplore/base/templates/base/login_register.html
  UniExplore/base/templates/base/myResponses.html
  UniExplore/base/templates/base/profile.html
  UniExplore/base/templates/base/recentActivity.html
  UniExplore/base/templates/base/userResponses.html
  UniExplore/base/templates/password/password_reset.html
  UniExplore/base/templates/password/password_reset_complete.html
  UniExplore/base/templates/password/password_reset_confirm.html
  UniExplore/base/templates/password/password_reset_done.html
  UniExplore/base/tests.py
  UniExplore/base/urls.py
  UniExplore/base/views.py
  UniExplore/graph_helper.py
Labels: Documentation

#55 Update views.py
  UniExplore/base/views.py
Labels: Changed Feature

#57 Styling create challenge
  UniExplore/base/templates/base/createChallenge.html
Labels: Styling

#59 Styling register page
  UniExplore/base/templates/base/login_register.html
Labels: Styling

#60 Styling done on sidebar
  UniExplore/base/templates/base/home.html
  UniExplore/templates/sidebar.html
Labels: Styling

#61 Added styling to feed sections
  UniExplore/base/templates/base/challengeResponses.html
  UniExplore/base/templates/base/leaderboard.html
  UniExplore/base/templates/base/myResponses.html
  UniExplore/base/templates/base/recentActivity.html
  UniExplore/templates/base.html
  UniExplore/templates/like.html
  UniExplore/templates/newbase.html
  UniExplore/templates/sidebar.html
Labels: Documentation, Styling

#64 Add logo to bottom of sidebar
  UniExplore/static/images/UniExploreLogo.png
  UniExplore/templates/sidebar.html
Labels: Styling

#65 changed sidebar
  UniExplore/UniExplore/settings.py
  UniExplore/templates/sidebar.html
Labels: Styling

#66 Styling additions
  UniExplore/base/templates/base/challengeResponses.html
  UniExplore/base/templates/base/home.html
  UniExplore/base/templates/base/leaderboard.html
  UniExplore/base/templates/base/profile.html
  UniExplore/base/templates/base/recentActivity.html
  UniExplore/base/templates/base/userResponses.html
Labels: Styling

#67 Login register fix
  UniExplore/auth_helper.py
  UniExplore/base/apps.py
  UniExplore/base/decorators.py
  UniExplore/base/forms.py
  UniExplore/base/models.py
  UniExplore/base/templates/base/createChallenge.html
  UniExplore/base/templates/base/createResponse.html
  UniExplore/base/templates/base/home.html
  UniExplore/base/templates/base/leaderboard.html
  UniExplore/base/templates/base/login_register.html
  UniExplore/base/templates/base/myResponses.html
  UniExplore/base/templates/base/profile.html
  UniExplore/base/templates/base/profile_edit.html
  UniExplore/base/templates/base/userResponses.html
  UniExplore/base/templates/password/password_reset.html
  UniExplore/base/templates/password/password_reset_complete.html
  UniExplore/base/templates/password/password_reset_confirm.html
  UniExplore/base/templates/password/password_reset_done.html
  UniExplore/base/templates/password/password_reset_email.txt
  UniExplore/base/urls.py
  UniExplore/base/views.py
  UniExplore/manage.py
Labels: Changed Feature, Refactoring

#69 Implemented program config in settings.py and added challenge creation range checking
  UniExplore/UniExplore/settings.py
  UniExplore/base/templates/base/createChallenge.html
  UniExplore/base/templates/base/home.html
  UniExplore/base/views.py
  requirements.txt
Labels: Changed Feature, Refactoring

#76 Split views.py
  UniExplore/base/auth_helper.py
  UniExplore/base/graph_helper.py
  UniExplore/base/views.py
  UniExplore/base/views/__init__.py
  UniExplore/base/views/challanges_and_responses.py
  UniExplore/base/views/home.py
  UniExplore/base/views/leaderboard.py
  UniExplore/base/views/likes.py
  UniExplore/base/views/lockout.py
  UniExplore/base/views/login.py
  UniExplore/base/views/password_reset.py
  UniExplore/base/views/profile.py
  UniExplore/base/views/recent_activity.py
  UniExplore/base/views/register.py
  UniExplore/base/views/sso.py
Labels: Refactoring

#77 Add an icon for the tab
  UniExplore/templates/base.html
  UniExplore/templates/sidebar.html
Labels: Styling

#75 Add photos to challenge responses
  UniExplore/base/forms.py
  UniExplore/base/migrations/0020_responses_photograph.py
  UniExplore/base/migrations/0021_alter_responses_photograph.py
  UniExplore/base/migrations/0022_alter_responses_photograph.py
  UniExplore/base/models.py
  UniExplore/base/templates/base/challengeResponses.html
  UniExplore/base/templates/base/createResponse.html
  UniExplore/base/templates/base/myResponses.html
  UniExplore/base/templates/base/profile.html
  UniExplore/base/templates/base/recentActivity.html
  UniExplore/base/templates/base/userResponses.html
  UniExplore/base/urls.py
  UniExplore/base/views/challanges_and_responses.py
  UniExplore/media/image_uploads/challenge-completed.png
  UniExplore/media/image_uploads/molecule.png
  UniExplore/media/profile_pictures/yoga-in-the-workplace.png
Labels: New Feature

#96 Role generation
  UniExplore/base/resources/sample_locations.json
  UniExplore/base/views/home.py
Labels: Changed Feature

#97 Updated git ignore to ignore image files
  .gitignore
  UniExplore/media/image_uploads/molecule.png
  UniExplore/media/profile_pictures/0C48EFD5-E014-4DB8-9642-49447CA49C37.JPG
  UniExplore/media/profile_pictures/8C5C7464-BDE3-4AF2-828E-C4ED0321996F.jpg
  UniExplore/media/profile_pictures/yoga-in-the-workplace.png
Labels: Documentation

#91 Alerts user to change their username
  UniExplore/base/models.py
  UniExplore/base/views/register.py
  UniExplore/base/views/sso.py
Labels: Fixed Bug, Changed Feature

#94 Email needs to be verified to login
  UniExplore/base/migrations/0034_profile_email_confirmed.py
  UniExplore/base/models.py
  UniExplore/base/templates/email_verification/account_activation_email.html
  UniExplore/base/tokens.py
  UniExplore/base/urls.py
  UniExplore/base/views/register.py
  requirements.txt
Labels: Changed Feature

#99 Delete account
  UniExplore/base/templates/base/deleteProfile.html
  UniExplore/base/templates/base/profile.html
  UniExplore/base/templates/base/profile_edit.html
  UniExplore/base/urls.py
  UniExplore/base/views/profile.py
Labels: New Feature

#98 Fixed bug
  UniExplore/base/tokens.py
  UniExplore/base/views/register.py
Labels: Fixed Bug

#100 Image obfuscation
  UniExplore/UniExplore/settings.py
  UniExplore/base/models.py
  UniExplore/base/resources/sample_locations.json
  UniExplore/base/views/profile.py
  requirements.txt
Labels: Fixed Bug, Changed Feature

#101 Upgrade user
  UniExplore/base/admin.py
  UniExplore/base/migrations/0035_upgrade.py
  UniExplore/base/models.py
  UniExplore/base/templates/base/profile.html
  UniExplore/base/templates/base/requestMaster.html
  UniExplore/base/templates/base/upgradeUser.html
  UniExplore/base/urls.py
  UniExplore/base/views/challanges_and_responses.py
  UniExplore/base/views/home.py
  UniExplore/base/views/profile.py
  UniExplore/templates/sidebar.html
Labels: New Feature

#102 Fix login css
  UniExplore/base/templates/base/login_register.html
Labels: Fixed Bug, Styling

#103 Implemented GDPR into the site
  UniExplore/base/templates/GDPR/ToS.html
  UniExplore/base/templates/GDPR/cookie.html
  UniExplore/base/templates/GDPR/privacyPolicy.html
  UniExplore/base/templates/base/home.html
  UniExplore/base/urls.py
  UniExplore/base/views/__init__.py
  UniExplore/base/views/gdpr.py
  UniExplore/templates/base.html
Labels: New Feature

#95 Styling cleanup
  UniExplore/base/templates/base/challengeResponses.html
  UniExplore/base/templates/base/createChallenge.html
  UniExplore/base/templates/base/myResponses.html
  UniExplore/base/templates/base/profile.html
  UniExplore/base/templates/base/recentActivity.html
  UniExplore/base/templates/base/userResponses.html
  UniExplore/static/StyleSheet.css
  UniExplore/templates/sidebar.html
Labels: Styling

#104 Add dev mode and fix image analysis bug
  UniExplore/base/views/challanges_and_responses.py
  UniExplore/base/views/profile.py
Labels: Fixed Bug, Changed Feature

#106 Add button to make users accept terms and conditions before proceeding
  UniExplore/base/templates/base/login_register.html
Labels: Changed Feature

#90 Added necessary config to get django to work with apache
  UniExplore/UniExplore/settings.py
  UniExplore/base/urls.py
  requirements.txt
Labels: Changed Feature

#108 Force user login
  UniExplore/UniExplore/settings.py
  UniExplore/base/templates/base/login_register.html
  UniExplore/base/views/home.py
Labels: Changed Feature

#110 Spoof mode restriction & hardcoded challenges
  UniExplore/base/templates/base/home.html
  UniExplore/base/views/challanges_and_responses.py
Labels: Changed Feature

#109 Image fixes
  UniExplore/UniExplore/settings.py
  UniExplore/base/models.py
  UniExplore/base/views/profile.py
  UniExplore/static/StyleSheet.css
Labels: Fixed Bug

#113 Update requirements.txt
  requirements.txt
Labels: Changed Feature

#117 Update requirements.txt
  requirements.txt
Labels: Refactoring

#119 Deleting posts
  UniExplore/base/migrations/0038_merge_20220323_1156.py
  UniExplore/base/templates/base/challengeResponses.html
  UniExplore/base/templates/base/deletePost.html
  UniExplore/base/templates/base/myResponses.html
  UniExplore/base/templates/base/profile.html
  UniExplore/base/templates/base/recentActivity.html
  UniExplore/base/templates/base/userResponses.html
  UniExplore/base/urls.py
  UniExplore/base/views/challanges_and_responses.py
Labels: New Feature

#125 Delete comments
  UniExplore/base/migrations/0039_alter_profile_following.py
  UniExplore/base/templates/base/deleteComment.html
  UniExplore/base/templates/base/viewComments.html
  UniExplore/base/urls.py
  UniExplore/base/views/comments.py
Labels: New Feature

#126 Update sidebar
  UniExplore/static/StyleSheet.css
  UniExplore/templates/base.html
  UniExplore/templates/sidebar.html
Labels: Fixed Bug, Styling

#127 fixed reporting posts
  UniExplore/base/migrations/0040_remove_reportposts_comment_reportposts_post.py
  UniExplore/base/models.py
Labels: Fixed Bug

#133 Fixed lockout bug
  UniExplore/base/views/lockout.py
Labels: Fixed Bug
